<script setup>

</script>

<template>
    <div class="bg-my-gray grow gap-5 text-white">
        <h1 class="text-4xl font-semibold mb-10">Lorem, ipsum dolor.</h1>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Suscipit quidem inventore hic magnam saepe corrupti quis, vel necessitatibus? Asperiores dolorum eaque magnam quas quod tempore minima quia labore expedita blanditiis molestiae a maxime aliquid cum quasi cupiditate, omnis rerum veritatis? Tempora voluptatum incidunt labore dolore dolor! Doloremque iste quia rerum omnis laboriosam ad perspiciatis nemo id optio aspernatur recusandae hic voluptatem non vel harum, sed laborum iusto neque repellendus deleniti? Odit, obcaecati. Iusto commodi esse odit aut odio nemo aliquid unde aspernatur natus et, asperiores fugit illo cupiditate quo! Maxime, modi eius. Consequuntur optio culpa ducimus corporis saepe voluptatem consequatur!</p>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Suscipit quidem inventore hic magnam saepe corrupti quis, vel necessitatibus? Asperiores dolorum eaque magnam quas quod tempore minima quia labore expedita blanditiis molestiae a maxime aliquid cum quasi cupiditate, omnis rerum veritatis? Tempora voluptatum incidunt labore dolore dolor! Doloremque iste quia rerum omnis laboriosam ad perspiciatis nemo id optio aspernatur recusandae hic voluptatem non vel harum, sed laborum iusto neque repellendus deleniti? Odit, obcaecati. Iusto commodi esse odit aut odio nemo aliquid unde aspernatur natus et, asperiores fugit illo cupiditate quo! Maxime, modi eius. Consequuntur optio culpa ducimus corporis saepe voluptatem consequatur!</p>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Suscipit quidem inventore hic magnam saepe corrupti quis, vel necessitatibus? Asperiores dolorum eaque magnam quas quod tempore minima quia labore expedita blanditiis molestiae a maxime aliquid cum quasi cupiditate, omnis rerum veritatis? Tempora voluptatum incidunt labore dolore dolor! Doloremque iste quia rerum omnis laboriosam ad perspiciatis nemo id optio aspernatur recusandae hic voluptatem non vel harum, sed laborum iusto neque repellendus deleniti? Odit, obcaecati. Iusto commodi esse odit aut odio nemo aliquid unde aspernatur natus et, asperiores fugit illo cupiditate quo! Maxime, modi eius. Consequuntur optio culpa ducimus corporis saepe voluptatem consequatur!</p>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Suscipit quidem inventore hic magnam saepe corrupti quis, vel necessitatibus? Asperiores dolorum eaque magnam quas quod tempore minima quia labore expedita blanditiis molestiae a maxime aliquid cum quasi cupiditate, omnis rerum veritatis? Tempora voluptatum incidunt labore dolore dolor! Doloremque iste quia rerum omnis laboriosam ad perspiciatis nemo id optio aspernatur recusandae hic voluptatem non vel harum, sed laborum iusto neque repellendus deleniti? Odit, obcaecati. Iusto commodi esse odit aut odio nemo aliquid unde aspernatur natus et, asperiores fugit illo cupiditate quo! Maxime, modi eius. Consequuntur optio culpa ducimus corporis saepe voluptatem consequatur!</p>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Suscipit quidem inventore hic magnam saepe corrupti quis, vel necessitatibus? Asperiores dolorum eaque magnam quas quod tempore minima quia labore expedita blanditiis molestiae a maxime aliquid cum quasi cupiditate, omnis rerum veritatis? Tempora voluptatum incidunt labore dolore dolor! Doloremque iste quia rerum omnis laboriosam ad perspiciatis nemo id optio aspernatur recusandae hic voluptatem non vel harum, sed laborum iusto neque repellendus deleniti? Odit, obcaecati. Iusto commodi esse odit aut odio nemo aliquid unde aspernatur natus et, asperiores fugit illo cupiditate quo! Maxime, modi eius. Consequuntur optio culpa ducimus corporis saepe voluptatem consequatur!</p>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Suscipit quidem inventore hic magnam saepe corrupti quis, vel necessitatibus? Asperiores dolorum eaque magnam quas quod tempore minima quia labore expedita blanditiis molestiae a maxime aliquid cum quasi cupiditate, omnis rerum veritatis? Tempora voluptatum incidunt labore dolore dolor! Doloremque iste quia rerum omnis laboriosam ad perspiciatis nemo id optio aspernatur recusandae hic voluptatem non vel harum, sed laborum iusto neque repellendus deleniti? Odit, obcaecati. Iusto commodi esse odit aut odio nemo aliquid unde aspernatur natus et, asperiores fugit illo cupiditate quo! Maxime, modi eius. Consequuntur optio culpa ducimus corporis saepe voluptatem consequatur!</p>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Suscipit quidem inventore hic magnam saepe corrupti quis, vel necessitatibus? Asperiores dolorum eaque magnam quas quod tempore minima quia labore expedita blanditiis molestiae a maxime aliquid cum quasi cupiditate, omnis rerum veritatis? Tempora voluptatum incidunt labore dolore dolor! Doloremque iste quia rerum omnis laboriosam ad perspiciatis nemo id optio aspernatur recusandae hic voluptatem non vel harum, sed laborum iusto neque repellendus deleniti? Odit, obcaecati. Iusto commodi esse odit aut odio nemo aliquid unde aspernatur natus et, asperiores fugit illo cupiditate quo! Maxime, modi eius. Consequuntur optio culpa ducimus corporis saepe voluptatem consequatur!</p>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Suscipit quidem inventore hic magnam saepe corrupti quis, vel necessitatibus? Asperiores dolorum eaque magnam quas quod tempore minima quia labore expedita blanditiis molestiae a maxime aliquid cum quasi cupiditate, omnis rerum veritatis? Tempora voluptatum incidunt labore dolore dolor! Doloremque iste quia rerum omnis laboriosam ad perspiciatis nemo id optio aspernatur recusandae hic voluptatem non vel harum, sed laborum iusto neque repellendus deleniti? Odit, obcaecati. Iusto commodi esse odit aut odio nemo aliquid unde aspernatur natus et, asperiores fugit illo cupiditate quo! Maxime, modi eius. Consequuntur optio culpa ducimus corporis saepe voluptatem consequatur!</p>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Suscipit quidem inventore hic magnam saepe corrupti quis, vel necessitatibus? Asperiores dolorum eaque magnam quas quod tempore minima quia labore expedita blanditiis molestiae a maxime aliquid cum quasi cupiditate, omnis rerum veritatis? Tempora voluptatum incidunt labore dolore dolor! Doloremque iste quia rerum omnis laboriosam ad perspiciatis nemo id optio aspernatur recusandae hic voluptatem non vel harum, sed laborum iusto neque repellendus deleniti? Odit, obcaecati. Iusto commodi esse odit aut odio nemo aliquid unde aspernatur natus et, asperiores fugit illo cupiditate quo! Maxime, modi eius. Consequuntur optio culpa ducimus corporis saepe voluptatem consequatur!</p>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Suscipit quidem inventore hic magnam saepe corrupti quis, vel necessitatibus? Asperiores dolorum eaque magnam quas quod tempore minima quia labore expedita blanditiis molestiae a maxime aliquid cum quasi cupiditate, omnis rerum veritatis? Tempora voluptatum incidunt labore dolore dolor! Doloremque iste quia rerum omnis laboriosam ad perspiciatis nemo id optio aspernatur recusandae hic voluptatem non vel harum, sed laborum iusto neque repellendus deleniti? Odit, obcaecati. Iusto commodi esse odit aut odio nemo aliquid unde aspernatur natus et, asperiores fugit illo cupiditate quo! Maxime, modi eius. Consequuntur optio culpa ducimus corporis saepe voluptatem consequatur!</p>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Suscipit quidem inventore hic magnam saepe corrupti quis, vel necessitatibus? Asperiores dolorum eaque magnam quas quod tempore minima quia labore expedita blanditiis molestiae a maxime aliquid cum quasi cupiditate, omnis rerum veritatis? Tempora voluptatum incidunt labore dolore dolor! Doloremque iste quia rerum omnis laboriosam ad perspiciatis nemo id optio aspernatur recusandae hic voluptatem non vel harum, sed laborum iusto neque repellendus deleniti? Odit, obcaecati. Iusto commodi esse odit aut odio nemo aliquid unde aspernatur natus et, asperiores fugit illo cupiditate quo! Maxime, modi eius. Consequuntur optio culpa ducimus corporis saepe voluptatem consequatur!</p>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Suscipit quidem inventore hic magnam saepe corrupti quis, vel necessitatibus? Asperiores dolorum eaque magnam quas quod tempore minima quia labore expedita blanditiis molestiae a maxime aliquid cum quasi cupiditate, omnis rerum veritatis? Tempora voluptatum incidunt labore dolore dolor! Doloremque iste quia rerum omnis laboriosam ad perspiciatis nemo id optio aspernatur recusandae hic voluptatem non vel harum, sed laborum iusto neque repellendus deleniti? Odit, obcaecati. Iusto commodi esse odit aut odio nemo aliquid unde aspernatur natus et, asperiores fugit illo cupiditate quo! Maxime, modi eius. Consequuntur optio culpa ducimus corporis saepe voluptatem consequatur!</p>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Suscipit quidem inventore hic magnam saepe corrupti quis, vel necessitatibus? Asperiores dolorum eaque magnam quas quod tempore minima quia labore expedita blanditiis molestiae a maxime aliquid cum quasi cupiditate, omnis rerum veritatis? Tempora voluptatum incidunt labore dolore dolor! Doloremque iste quia rerum omnis laboriosam ad perspiciatis nemo id optio aspernatur recusandae hic voluptatem non vel harum, sed laborum iusto neque repellendus deleniti? Odit, obcaecati. Iusto commodi esse odit aut odio nemo aliquid unde aspernatur natus et, asperiores fugit illo cupiditate quo! Maxime, modi eius. Consequuntur optio culpa ducimus corporis saepe voluptatem consequatur!</p>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Suscipit quidem inventore hic magnam saepe corrupti quis, vel necessitatibus? Asperiores dolorum eaque magnam quas quod tempore minima quia labore expedita blanditiis molestiae a maxime aliquid cum quasi cupiditate, omnis rerum veritatis? Tempora voluptatum incidunt labore dolore dolor! Doloremque iste quia rerum omnis laboriosam ad perspiciatis nemo id optio aspernatur recusandae hic voluptatem non vel harum, sed laborum iusto neque repellendus deleniti? Odit, obcaecati. Iusto commodi esse odit aut odio nemo aliquid unde aspernatur natus et, asperiores fugit illo cupiditate quo! Maxime, modi eius. Consequuntur optio culpa ducimus corporis saepe voluptatem consequatur!</p>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Suscipit quidem inventore hic magnam saepe corrupti quis, vel necessitatibus? Asperiores dolorum eaque magnam quas quod tempore minima quia labore expedita blanditiis molestiae a maxime aliquid cum quasi cupiditate, omnis rerum veritatis? Tempora voluptatum incidunt labore dolore dolor! Doloremque iste quia rerum omnis laboriosam ad perspiciatis nemo id optio aspernatur recusandae hic voluptatem non vel harum, sed laborum iusto neque repellendus deleniti? Odit, obcaecati. Iusto commodi esse odit aut odio nemo aliquid unde aspernatur natus et, asperiores fugit illo cupiditate quo! Maxime, modi eius. Consequuntur optio culpa ducimus corporis saepe voluptatem consequatur!</p>
    </div>
</template>

<style scoped>

</style>